# vim:ts=2:sw=2:et
dist: trusty

language: php

php:
  - nightly

services:
  - mysql
  - postgresql

before_script:
  - composer update --dev
  - mysql -e "CREATE DATABASE test CHARACTER SET 'UTF8';"
  - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test'; GRANT ALL ON *.* TO 'test'@'localhost'";
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'; GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

script:
  - cd test && ../vendor/bin/run_unit_tests
